/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('attractions').del();
  await knex('attractions').insert([
    {
      id: 1,
      city_id: 1,
      attraction_name: 'Cenote Dos Ojos',
      category: 'Natural Wonder',
      description: 'A stunning cenote with crystal-clear waters, perfect for snorkeling and diving. It features an impressive cave system and is one of the most famous cenotes in the Yucatan Peninsula.',
      best_time_to_visit: 'Mid-morning for clear waters and fewer crowds',
      hours: '08:00 AM to 05:00 PM',
      fee: 'MXN 200',
      nearby_attraction: 'Tulum, Xel-Há Park',
      travel_tips: 'Bring your snorkeling gear and an underwater camera to capture the beauty of the cenote. Arrive early to enjoy the site with fewer visitors.',
      attraction_image_path: 'http://localhost:8080/images/cancun/cenote-dos-ojos.png'
    },
    {
      id: 2,
      city_id: 1,
      attraction_name: 'Chichén Itzá',
      category: 'Archaeological Site',
      description: 'A UNESCO World Heritage Site and one of the New Seven Wonders of the World, Chichén Itzá is an ancient Mayan city with the iconic pyramid, El Castillo.',
      best_time_to_visit: 'Early morning to avoid the heat and crowds',
      hours: '08:00 AM to 05:00 PM',
      fee: 'MXN 480 (INAH fee)',
      nearby_attraction: 'Ik Kil Cenote, Valladolid',
      travel_tips: 'Bring water, a hat, and sunscreen. Consider hiring a guide to learn more about the history of the site.',
      attraction_image_path: 'http://localhost:8080/images/cancun/chichén-itzá.png'
    },
    {
      id: 3,
      city_id: 1,
      attraction_name: 'El Rey Ruins',
      category: 'Archaeological Site',
      description: 'Located in Cancun’s hotel zone, the El Rey Ruins offer a quick look into Mayan history with a smaller and more accessible set of ruins. Iguanas often sunbathe on the stones.',
      best_time_to_visit: 'Late morning or early afternoon',
      hours: '08:00 AM to 05:00 PM',
      fee: 'MXN 70',
      nearby_attraction: 'Dolphin Beach (Playa Delfines), Museo Maya de Cancún',
      travel_tips: 'Wear comfortable shoes and take a walk along the beach at Playa Delfines after visiting the ruins.',
      attraction_image_path: 'http://localhost:8080/images/cancun/el-rey-ruins.png'
    },
    {
      id: 4,
      city_id: 1,
      attraction_name: 'Playa Delfines',
      category: 'Beach',
      description: 'One of Cancun’s most beautiful public beaches, Playa Delfines is known for its soft white sand, clear waters, and the famous Cancun sign.',
      best_time_to_visit: 'Early morning for a peaceful experience or afternoon for a lively beach atmosphere',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'El Rey Ruins, Dolphin Watching Tours',
      travel_tips: 'Arrive early to take photos at the Cancun sign before it gets crowded. There are no beach clubs, so bring your own food and drinks.',
      attraction_image_path: 'http://localhost:8080/images/cancun/playa-delfines.png'
    },
    {
      id: 5,
      city_id: 1,
      attraction_name: 'Xcaret Park',
      category: 'Eco-park',
      description: 'A massive eco-archaeological park featuring wildlife, snorkeling in underground rivers, cultural performances, and exhibits of Mexico’s history.',
      best_time_to_visit: 'Morning to enjoy a full day at the park',
      hours: '08:30 AM to 10:30 PM',
      fee: 'MXN 1,800 for general admission',
      nearby_attraction: 'Xplor Park, Xel-Há Park',
      travel_tips: 'Plan to spend the entire day at Xcaret. Wear comfortable clothes and bring a swimsuit for the water activities. Book tickets online for discounts.',
      attraction_image_path: 'http://localhost:8080/images/cancun/xcaret-park.png'
    },
    {
      id: 6,
      city_id: 2,
      attraction_name: 'La Sagrada Família',
      category: 'Basilica',
      description: 'An iconic basilica designed by Antoni Gaudí, still under construction since 1882. It’s a UNESCO World Heritage Site and one of the most visited landmarks in Spain.',
      best_time_to_visit: 'Early morning to avoid crowds',
      hours: '09:00 AM to 06:00 PM',
      fee: '€26 (donations for preservation appreciated)',
      nearby_attraction: 'Casa Milà, Casa Batlló, Park Güell',
      travel_tips: 'Pre-book tickets to skip the long queues, visit early morning or late afternoon for fewer crowds.',
      attraction_image_path: 'http://localhost:8080/images/barcelona/sagrada-familia.png'
    },
    {
      id: 7,
      city_id: 2,
      attraction_name: 'Park Güell',
      category: 'Park',
      description: 'A colorful public park designed by Gaudí, offering stunning views of Barcelona. It’s famous for its unique architecture, mosaic work, and artistic landscaping.',
      best_time_to_visit: 'Morning or late afternoon for cooler weather and fewer tourists',
      hours: '08:00 AM to 09:30 PM',
      fee: '€10',
      nearby_attraction: 'La Sagrada Família, Gràcia District',
      travel_tips: 'Wear comfortable shoes, as the park involves a lot of walking. Visit during the off-season to avoid crowds.',
      attraction_image_path: 'http://localhost:8080/images/barcelona/park-güell.png'
    },
    {
      id: 8,
      city_id: 2,
      attraction_name: 'Casa Batlló',
      category: 'Historical House',
      description: 'A masterpiece by Gaudí, this modernist building is famous for its colorful facade and whimsical architecture.',
      best_time_to_visit: 'Early afternoon for the best light on the facade',
      hours: '09:00 AM to 08:00 PM',
      fee: '€25',
      nearby_attraction: 'La Pedrera (Casa Milà), Passeig de Gràcia',
      travel_tips: 'Audio guides are available for a self-guided tour. Visit in the afternoon to capture the facade under the best lighting.',
      attraction_image_path: 'http://localhost:8080/images/barcelona/casa-batlló.png'
    },
    {
      id: 9,
      city_id: 2,
      attraction_name: 'La Rambla',
      category: 'Street/Promenade',
      description: 'Barcelona’s famous tree-lined street, filled with shops, cafes, and street performers. It stretches from Plaça de Catalunya to the waterfront.',
      best_time_to_visit: 'Late afternoon for a lively atmosphere',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Boqueria Market, Columbus Monument',
      travel_tips: 'Beware of pickpockets, especially in crowded areas. Enjoy street food from the local vendors at Boqueria Market.',
      attraction_image_path: 'http://localhost:8080/images/barcelona/la-rambla.png'
    },
    {
      id: 10,
      city_id: 2,
      attraction_name: 'Camp Nou',
      category: 'Stadium',
      description: 'The home stadium of FC Barcelona, one of the most famous football teams in the world. Visitors can tour the stadium and visit the FC Barcelona Museum.',
      best_time_to_visit: 'Morning for tours, or match days for a thrilling experience',
      hours: '10:00 AM to 06:00 PM (varies on match days)',
      fee: '€28 for a stadium tour',
      nearby_attraction: 'FC Barcelona Museum, Les Corts District',
      travel_tips: 'Book tickets in advance for both tours and matches. If attending a game, arrive early for the pre-match atmosphere.',
      attraction_image_path: 'http://localhost:8080/images/barcelona/camp-nou.png'
    },
    {
      id: 11,
      city_id: 3,
      attraction_name: 'Hagia Sophia',
      category: 'Historical Monument',
      description: 'Originally built as a cathedral in 537 AD, later converted into a mosque, and now a mosque again. Hagia Sophia is one of Istanbul’s most significant and iconic landmarks.',
      best_time_to_visit: 'Early morning or late afternoon to avoid crowds',
      hours: '09:00 AM to 05:00 PM (Closed during prayer times)',
      fee: 'Free entry (donations appreciated)',
      nearby_attraction: 'Blue Mosque, Topkapi Palace, Basilica Cistern',
      travel_tips: 'Visit during non-prayer times to explore inside. No flash photography is allowed, and modest dress is required.',
      attraction_image_path: 'http://localhost:8080/images/istanbul/hagia-sophia.png'
    },
    {
      id: 12,
      city_id: 3,
      attraction_name: 'Blue Mosque',
      category: 'Mosque',
      description: 'The Blue Mosque, known for its beautiful blue tilework and grand design, is one of Istanbul’s most important religious sites and a stunning example of Ottoman architecture.',
      best_time_to_visit: 'Outside of prayer times, particularly in the morning',
      hours: '08:30 AM to 06:30 PM (Closed during prayer times)',
      fee: 'Free entry',
      nearby_attraction: 'Hagia Sophia, Basilica Cistern, Hippodrome',
      travel_tips: 'Dress modestly (women must cover their heads). Shoes must be removed before entering. Visit early to avoid long queues.',
      attraction_image_path: 'http://localhost:8080/images/istanbul/blue-mosque.png'
    },
    {
      id: 13,
      city_id: 3,
      attraction_name: 'Dolmabahçe Palace',
      category: 'Palace',
      description: 'An opulent 19th-century palace located along the Bosphorus, Dolmabahçe Palace was the main administrative center of the Ottoman Empire and showcases stunning European-style architecture.',
      best_time_to_visit: 'Morning to avoid large crowds',
      hours: '09:00 AM to 04:00 PM (Closed on Mondays)',
      fee: '80 Turkish Lira for general admission',
      nearby_attraction: 'Bosphorus Cruise, Taksim Square',
      travel_tips: 'Wear comfortable shoes, as the palace grounds are extensive. Photography is not allowed inside the palace.',
      attraction_image_path: 'http://localhost:8080/images/istanbul/dolmabahçe-palace.png'
    },
    {
      id: 14,
      city_id: 3,
      attraction_name: 'Grand Bazaar',
      category: 'Market',
      description: 'One of the largest and oldest covered markets in the world, the Grand Bazaar is a vibrant maze of shops selling everything from textiles and jewelry to spices and antiques.',
      best_time_to_visit: 'Morning to avoid the busiest times',
      hours: '08:30 AM to 07:00 PM (Closed on Sundays)',
      fee: 'Free entry',
      nearby_attraction: 'Spice Bazaar, Suleymaniye Mosque',
      travel_tips: 'Bargain with sellers for better prices. Keep an eye on your belongings in crowded areas.',
      attraction_image_path: 'http://localhost:8080/images/istanbul/grand-bazaar.png'
    },
    {
      id: 15,
      city_id: 3,
      attraction_name: 'Basilica Cistern',
      category: 'Underground Cistern',
      description: 'An ancient subterranean water reservoir featuring hundreds of columns, dim lighting, and the famous Medusa head sculptures at the base of two columns.',
      best_time_to_visit: 'Morning or early afternoon',
      hours: '09:00 AM to 05:30 PM',
      fee: '30 Turkish Lira',
      nearby_attraction: 'Hagia Sophia, Blue Mosque',
      travel_tips: 'Wear comfortable shoes, as the floors can be slippery. The cistern is dimly lit, so be prepared for low-light conditions.',
      attraction_image_path: 'http://localhost:8080/images/istanbul/basilica-cistern.png'
    },
    {
      id: 16,
      city_id: 4,
      attraction_name: 'Buckingham Palace',
      category: 'Palace',
      description: 'The official London residence of the British monarch, Buckingham Palace is an iconic landmark. Visitors can witness the Changing of the Guard and tour the palace’s State Rooms during the summer.',
      best_time_to_visit: 'Morning for the Changing of the Guard ceremony',
      hours: '09:30 AM to 06:00 PM (Summer State Room tours)',
      fee: '£26.50 for a tour of the State Rooms',
      nearby_attraction: 'St. James’s Park, The Mall',
      travel_tips: 'Arrive early to secure a good spot for the Changing of the Guard. Pre-book tickets for State Room tours during the summer.',
      attraction_image_path: 'http://localhost:8080/images/london/buckingham-palace.png'
    },
    {
      id: 17,
      city_id: 4,
      attraction_name: 'Houses of Parliament',
      category: 'Government Building',
      description: 'The Houses of Parliament, also known as the Palace of Westminster, is home to the UK Parliament. Visitors can tour the building and see Big Ben, the iconic clock tower.',
      best_time_to_visit: 'Morning or during scheduled tours',
      hours: 'Various times depending on tour schedules',
      fee: '£22 for a guided tour',
      nearby_attraction: 'Big Ben, Westminster Abbey',
      travel_tips: 'Book tours in advance, especially for summer visits. Photography is restricted inside certain areas.',
      attraction_image_path: 'http://localhost:8080/images/london/houses-of-parliament.png'
    },
    {
      id: 18,
      city_id: 4,
      attraction_name: 'The National Gallery',
      category: 'Art Museum',
      description: 'Located in Trafalgar Square, The National Gallery houses a vast collection of Western European paintings from the 13th to the 19th centuries, including works by Van Gogh, Da Vinci, and Turner.',
      best_time_to_visit: 'Late afternoon for a quieter experience',
      hours: '10:00 AM to 06:00 PM',
      fee: 'Free entry (donations welcome)',
      nearby_attraction: 'Trafalgar Square, Covent Garden',
      travel_tips: 'Take a free guided tour for more context on the art. Avoid weekends to experience the museum with fewer crowds.',
      attraction_image_path: 'http://localhost:8080/images/london/the-national-gallery.png'
    },
    {
      id: 19,
      city_id: 4,
      attraction_name: 'Tower of London',
      category: 'Fortress/Castle',
      description: 'A historic castle located on the banks of the Thames, the Tower of London is famous for housing the Crown Jewels, being a former royal residence, and its history as a prison.',
      best_time_to_visit: 'Morning for fewer crowds',
      hours: '09:00 AM to 05:30 PM (varies by season)',
      fee: '£29.90 for general admission',
      nearby_attraction: 'Tower Bridge, The Shard',
      travel_tips: 'Visit early to avoid long lines for the Crown Jewels. Take a guided tour with a Beefeater to learn about the Tower’s history.',
      attraction_image_path: 'http://localhost:8080/images/london/tower-of-london.png'
    },
    {
      id: 20,
      city_id: 4,
      attraction_name: 'Westminster Abbey',
      category: 'Religious Site',
      description: 'A Gothic abbey church and UNESCO World Heritage Site, Westminster Abbey is known for hosting royal coronations and weddings, including that of Prince William and Kate Middleton.',
      best_time_to_visit: 'Mid-morning or late afternoon for fewer tourists',
      hours: '09:30 AM to 03:30 PM (Closed on Sundays for services)',
      fee: '£25 for general admission',
      nearby_attraction: 'Houses of Parliament, Big Ben',
      travel_tips: 'Book tickets online to avoid queues. Photography is not allowed inside the abbey.',
      attraction_image_path: 'http://localhost:8080/images/london/westminster-abbey.png'
    },
    {
      id: 21,
      city_id: 5,
      attraction_name: 'Arbat Street',
      category: 'Street/Promenade',
      description: 'One of Moscow’s oldest streets, Arbat is a lively pedestrian street filled with shops, cafes, street performers, and historical buildings. It’s a hub of art, culture, and history.',
      best_time_to_visit: 'Late afternoon for a lively atmosphere',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Pushkin Museum, Gogol House',
      travel_tips: 'Explore the local art galleries and cafes. Visit during the day to experience the vibrant street performances.',
      attraction_image_path: 'http://localhost:8080/images/moscow/arbat-street.png'
    },
    {
      id: 22,
      city_id: 5,
      attraction_name: 'Bolshoi Theatre',
      category: 'Theatre',
      description: 'The Bolshoi Theatre is one of the most famous theatres in the world, known for its ballet and opera performances. Its grand architecture and performances make it a must-visit in Moscow.',
      best_time_to_visit: 'Evening for a performance',
      hours: 'Performance times vary',
      fee: 'Prices vary based on the performance',
      nearby_attraction: 'Red Square, State Historical Museum',
      travel_tips: 'Book tickets in advance, especially for popular performances. Dress formally if attending a ballet or opera.',
      attraction_image_path: 'http://localhost:8080/images/moscow/bolshoi-theatre.png'
    },
    {
      id: 23,
      city_id: 5,
      attraction_name: 'Kremlin',
      category: 'Fortress/Government Building',
      description: 'The Moscow Kremlin is a fortified complex at the heart of Moscow, housing the official residence of the Russian president, several museums, and churches.',
      best_time_to_visit: 'Morning to avoid crowds',
      hours: '09:30 AM to 06:00 PM',
      fee: '700 RUB for general admission to the Armoury Chamber',
      nearby_attraction: 'Red Square, Lenin’s Mausoleum',
      travel_tips: 'Book tickets online to avoid queues. Guided tours are recommended to fully understand the rich history of the Kremlin.',
      attraction_image_path: 'http://localhost:8080/images/moscow/kremlin.png'
    },
    {
      id: 24,
      city_id: 5,
      attraction_name: 'Saint Basil’s Cathedral',
      category: 'Cathedral',
      description: 'Famous for its colorful onion domes, Saint Basil’s Cathedral is an architectural masterpiece located in Red Square. It’s one of Russia’s most iconic landmarks.',
      best_time_to_visit: 'Morning for fewer tourists',
      hours: '11:00 AM to 05:00 PM',
      fee: '700 RUB for general admission',
      nearby_attraction: 'Kremlin, GUM Shopping Mall',
      travel_tips: 'The best views of the cathedral are from Red Square. Book tickets online to avoid long queues.',
      attraction_image_path: 'http://localhost:8080/images/moscow/saint-basils-cathedral.png'
    },
    {
      id: 25,
      city_id: 5,
      attraction_name: 'State Historical Museum',
      category: 'Museum',
      description: 'Located in Red Square, the State Historical Museum showcases Russian history from ancient times to the present, with exhibitions on archaeology, art, and royal artifacts.',
      best_time_to_visit: 'Late morning or early afternoon',
      hours: '10:00 AM to 06:00 PM (Closed on Tuesdays)',
      fee: '500 RUB for general admission',
      nearby_attraction: 'Red Square, Saint Basil’s Cathedral',
      travel_tips: 'Plan to spend a few hours exploring the vast collection. English audio guides are available.',
      attraction_image_path: 'http://localhost:8080/images/moscow/state-historical-museum.png'
    },
    {
      id: 26,
      city_id: 6,
      attraction_name: 'Champs-Élysées',
      category: 'Street/Promenade',
      description: 'One of the most famous avenues in the world, the Champs-Élysées is known for its theaters, cafés, and luxury shops. It stretches from the Arc de Triomphe to the Place de la Concorde.',
      best_time_to_visit: 'Afternoon for shopping or an evening stroll',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Arc de Triomphe, Place de la Concorde',
      travel_tips: 'Visit in the evening to see the avenue beautifully lit up. Make sure to stop by a café for a quintessential Parisian experience.',
      attraction_image_path: 'http://localhost:8080/images/paris/champs-elysées.png'
    },
    {
      id: 27,
      city_id: 6,
      attraction_name: 'Louvre Museum',
      category: 'Museum',
      description: 'The world’s largest and most visited art museum, the Louvre is home to thousands of works, including the Mona Lisa and the Venus de Milo.',
      best_time_to_visit: 'Early morning or late afternoon to avoid the crowds',
      hours: '09:00 AM to 06:00 PM (Closed on Tuesdays)',
      fee: '€17 for general admission',
      nearby_attraction: 'Jardin des Tuileries, Musée d’Orsay',
      travel_tips: 'Pre-book your tickets to skip the lines. Focus on a specific section of the museum if you’re short on time.',
      attraction_image_path: 'http://localhost:8080/images/paris/louvre-museum.png'
    },
    {
      id: 28,
      city_id: 6,
      attraction_name: 'Luxembourg Gardens',
      category: 'Garden/Park',
      description: 'A beautiful public park in Paris, the Luxembourg Gardens are known for their peaceful atmosphere, fountains, statues, and the stunning Luxembourg Palace.',
      best_time_to_visit: 'Morning for a peaceful stroll or afternoon to relax',
      hours: '07:30 AM to 09:00 PM',
      fee: 'Free entry',
      nearby_attraction: 'Panthéon, Saint-Sulpice Church',
      travel_tips: 'Bring a book and enjoy the serenity of the gardens. Great for a picnic or a relaxing break from sightseeing.',
      attraction_image_path: 'http://localhost:8080/images/paris/luxembourg-gardens.png'
    },
    {
      id: 29,
      city_id: 6,
      attraction_name: 'Notre-Dame Cathedral',
      category: 'Cathedral',
      description: 'One of the most famous Gothic cathedrals in the world, Notre-Dame is known for its architectural beauty, intricate stained glass windows, and its historical significance.',
      best_time_to_visit: 'Morning for fewer crowds',
      hours: 'Closed for restoration after the 2019 fire',
      fee: 'Free entry (donations for restoration appreciated)',
      nearby_attraction: 'Île de la Cité, Sainte-Chapelle',
      travel_tips: 'Admire the exterior from various vantage points along the Seine River. You can also view ongoing restoration efforts.',
      attraction_image_path: 'http://localhost:8080/images/paris/notre-dame-cathedral.png'
    },
    {
      id: 30,
      city_id: 6,
      attraction_name: 'Sacré-Cœur Basilica',
      category: 'Basilica',
      description: 'Situated at the highest point in Paris on Montmartre hill, Sacré-Cœur Basilica offers panoramic views of the city and features stunning white domes and mosaics.',
      best_time_to_visit: 'Early morning or late afternoon for stunning views',
      hours: '06:00 AM to 10:30 PM',
      fee: 'Free entry',
      nearby_attraction: 'Montmartre, Place du Tertre',
      travel_tips: 'Climb to the top of the dome for one of the best views of Paris. Visit Montmartre for an artistic experience after touring the basilica.',
      attraction_image_path: 'http://localhost:8080/images/paris/sacré-cœur-basilica.png'
    },
    {
      id: 31,
      city_id: 7,
      attraction_name: 'Christ the Redeemer',
      category: 'Statue',
      description: 'One of the New Seven Wonders of the World, Christ the Redeemer is a 30-meter-tall statue of Jesus Christ overlooking Rio from the Corcovado mountain.',
      best_time_to_visit: 'Early morning or late afternoon for fewer crowds and better lighting',
      hours: '08:00 AM to 07:00 PM',
      fee: 'R$97 for train tickets to the summit',
      nearby_attraction: 'Tijuca National Park, Sugarloaf Mountain',
      travel_tips: 'Arrive early to avoid the long lines. Consider taking the train or a hike up to the summit for stunning views.',
      attraction_image_path: 'http://localhost:8080/images/rio-de-janeiro/christ-the-redeemer.png'
    },
    {
      id: 32,
      city_id: 7,
      attraction_name: 'Copacabana Beach',
      category: 'Beach',
      description: 'One of the world’s most famous beaches, Copacabana Beach offers 4 kilometers of golden sand, lively atmosphere, and plenty of beachfront bars and restaurants.',
      best_time_to_visit: 'Morning or late afternoon for cooler weather',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Ipanema Beach, Sugarloaf Mountain',
      travel_tips: 'Bring sunscreen and stay hydrated. Try the local food and drinks from the beachside vendors.',
      attraction_image_path: 'http://localhost:8080/images/rio-de-janeiro/copacabana-beach.png'
    },
    {
      id: 33,
      city_id: 7,
      attraction_name: 'Maracanã Stadium',
      category: 'Stadium',
      description: 'One of the largest football stadiums in the world, Maracanã has hosted historic matches and events, including World Cup finals and Olympic ceremonies.',
      best_time_to_visit: 'Match day for the full experience',
      hours: '10:00 AM to 05:00 PM for stadium tours (varies on match days)',
      fee: 'R$50 for a stadium tour',
      nearby_attraction: 'Sambadrome, Rio de Janeiro Zoo',
      travel_tips: 'If visiting on a non-match day, take the guided tour to learn about the history of the stadium. On match days, arrive early for the pre-match atmosphere.',
      attraction_image_path: 'http://localhost:8080/images/rio-de-janeiro/maracanã-stadium.png'
    },
    {
      id: 34,
      city_id: 7,
      attraction_name: 'Selarón Steps',
      category: 'Public Art/Street',
      description: 'A famous staircase in Rio de Janeiro covered in colorful tiles from around the world, created by artist Jorge Selarón. The steps are a popular spot for photos and art lovers.',
      best_time_to_visit: 'Morning or late afternoon to avoid the heat',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Lapa Arches, Santa Teresa',
      travel_tips: 'Bring your camera to capture the vibrant colors of the tiles. Be mindful of your belongings, as it can get crowded.',
      attraction_image_path: 'http://localhost:8080/images/rio-de-janeiro/selarón-steps.png'
    },
    {
      id: 35,
      city_id: 7,
      attraction_name: 'Sugarloaf Mountain',
      category: 'Mountain/Natural Wonder',
      description: 'One of Rio’s most famous landmarks, Sugarloaf Mountain offers breathtaking panoramic views of the city and Guanabara Bay. Visitors can take a cable car to the summit.',
      best_time_to_visit: 'Late afternoon for sunset views',
      hours: '08:00 AM to 09:00 PM',
      fee: 'R$110 for a round-trip cable car ride',
      nearby_attraction: 'Christ the Redeemer, Botafogo Beach',
      travel_tips: 'Take the cable car up to the summit for amazing views. Visit in the late afternoon to catch the sunset over the city.',
      attraction_image_path: 'http://localhost:8080/images/rio-de-janeiro/sugarloaf-mountain.png'
    },
    {
      id: 36,
      city_id: 8,
      attraction_name: 'Colosseum',
      category: 'Historical Landmark',
      description: 'The Colosseum is an ancient Roman amphitheater and one of the most famous historical landmarks in the world. It once hosted gladiatorial combat and other public spectacles.',
      best_time_to_visit: 'Early morning or late afternoon to avoid crowds',
      hours: '08:30 AM to 07:00 PM',
      fee: '€16 for general admission',
      nearby_attraction: 'Roman Forum, Palatine Hill',
      travel_tips: 'Book tickets in advance to skip the lines. Take a guided tour to fully appreciate the history of the Colosseum.',
      attraction_image_path: 'http://localhost:8080/images/rome/colosseum.png'
    },
    {
      id: 37,
      city_id: 8,
      attraction_name: 'St. Peter’s Basilica',
      category: 'Basilica',
      description: 'Located in Vatican City, St. Peter’s Basilica is one of the largest and most renowned churches in the world. It features stunning Renaissance art and Michelangelo’s famous dome.',
      best_time_to_visit: 'Morning to avoid long lines',
      hours: '07:00 AM to 07:00 PM',
      fee: 'Free entry (dome climb costs €10)',
      nearby_attraction: 'Vatican Museums, Sistine Chapel',
      travel_tips: 'Visit early to avoid the lines. Climb to the top of the dome for panoramic views of Rome.',
      attraction_image_path: 'http://localhost:8080/images/rome/st-peters-basilica.png'
    },
    {
      id: 38,
      city_id: 8,
      attraction_name: 'The Pantheon',
      category: 'Historical Monument',
      description: 'A former Roman temple, now a church, The Pantheon is one of the best-preserved ancient monuments in Rome, known for its large domed ceiling and oculus.',
      best_time_to_visit: 'Morning or evening for fewer crowds',
      hours: '09:00 AM to 07:00 PM',
      fee: 'Free entry',
      nearby_attraction: 'Piazza Navona, Trevi Fountain',
      travel_tips: 'Visit early to appreciate the architecture without the crowds. Take time to explore the square around it.',
      attraction_image_path: 'http://localhost:8080/images/rome/the-pantheon.png'
    },
    {
      id: 39,
      city_id: 8,
      attraction_name: 'Trevi Fountain',
      category: 'Fountain',
      description: 'The Trevi Fountain is the largest and most famous fountain in Rome, known for its stunning Baroque architecture. Visitors traditionally throw coins into the fountain for good luck.',
      best_time_to_visit: 'Early morning or late evening for fewer crowds',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Spanish Steps, Piazza di Spagna',
      travel_tips: 'Visit at night to see the fountain beautifully lit up. Don’t forget to throw a coin in for good luck.',
      attraction_image_path: 'http://localhost:8080/images/rome/trevi-fountain.png'
    },
    {
      id: 40,
      city_id: 8,
      attraction_name: 'Vatican Museums',
      category: 'Museum',
      description: 'The Vatican Museums house one of the world’s greatest collections of art, including works by Michelangelo in the Sistine Chapel. It is a must-see for art lovers visiting Rome.',
      best_time_to_visit: 'Early morning or late afternoon to avoid crowds',
      hours: '09:00 AM to 06:00 PM (Closed Sundays)',
      fee: '€17 for general admission',
      nearby_attraction: 'St. Peter’s Basilica, Sistine Chapel',
      travel_tips: 'Pre-book tickets online to avoid long lines. Take a guided tour to fully appreciate the art collection.',
      attraction_image_path: 'http://localhost:8080/images/rome/vatican-museums.png'
    },
    {
      id: 41,
      city_id: 9,
      attraction_name: 'The Bund',
      category: 'Waterfront/Promenade',
      description: 'The Bund is a famous waterfront area in central Shanghai, known for its colonial-era buildings and stunning views of the modern skyline across the Huangpu River.',
      best_time_to_visit: 'Evening for the best view of the lit-up skyline',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Oriental Pearl Tower, Nanjing Road',
      travel_tips: 'Visit in the evening to see the skyline illuminated. Take a stroll along the promenade for great photo opportunities.',
      attraction_image_path: 'http://localhost:8080/images/shanghai/the-bund.png'
    },
    {
      id: 42,
      city_id: 9,
      attraction_name: 'Yu Garden',
      category: 'Garden',
      description: 'A classical Chinese garden in the heart of Shanghai, Yu Garden features pavilions, rockeries, ponds, and lush greenery, providing a peaceful retreat from the city.',
      best_time_to_visit: 'Morning for a quieter experience',
      hours: '08:30 AM to 05:00 PM',
      fee: '40 CNY for general admission',
      nearby_attraction: 'City God Temple, Old Town Market',
      travel_tips: 'Visit in the morning to avoid the crowds and fully appreciate the serene atmosphere. Don’t miss the City God Temple nearby.',
      attraction_image_path: 'http://localhost:8080/images/shanghai/yu-garden.png'
    },
    {
      id: 43,
      city_id: 9,
      attraction_name: 'Jade Buddha Temple',
      category: 'Temple',
      description: 'One of the most famous Buddhist temples in Shanghai, the Jade Buddha Temple is home to two jade Buddha statues, brought to China from Burma in the late 19th century.',
      best_time_to_visit: 'Morning to experience the temple’s peaceful atmosphere',
      hours: '08:00 AM to 04:30 PM',
      fee: '20 CNY for general admission',
      nearby_attraction: 'Jing’an Temple, People’s Square',
      travel_tips: 'Visit early to enjoy the peaceful ambiance. Respect temple etiquette and observe quietness while inside.',
      attraction_image_path: 'http://localhost:8080/images/shanghai/jade-buddha-temple.png'
    },
    {
      id: 44,
      city_id: 9,
      attraction_name: 'Nanjing Road',
      category: 'Shopping Street',
      description: 'Nanjing Road is one of the world’s busiest shopping streets, offering a wide range of shops, restaurants, and entertainment venues. It stretches over 5 kilometers through the heart of Shanghai.',
      best_time_to_visit: 'Afternoon for shopping, evening for the lights and atmosphere',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'People’s Square, The Bund',
      travel_tips: 'Explore Nanjing Road in the evening for a vibrant atmosphere with illuminated signs and bustling crowds. Wear comfortable shoes for walking.',
      attraction_image_path: 'http://localhost:8080/images/shanghai/nanjing-road.png'
    },
    {
      id: 45,
      city_id: 9,
      attraction_name: 'Shanghai Jewish Refugees Museum',
      category: 'Museum',
      description: 'The Shanghai Jewish Refugees Museum tells the story of the Jewish community that found refuge in Shanghai during World War II. It is located in the former Ohel Moishe Synagogue.',
      best_time_to_visit: 'Morning or early afternoon for a quieter experience',
      hours: '09:00 AM to 05:00 PM',
      fee: '50 CNY for general admission',
      nearby_attraction: 'Hongkou Park, Lu Xun Park',
      travel_tips: 'Visit the museum to learn about the unique history of the Jewish refugees in Shanghai. Allocate at least an hour to explore the exhibits.',
      attraction_image_path: 'http://localhost:8080/images/shanghai/shanghai-jewish-refugees-museum.png'
    },
    {
      id: 46,
      city_id: 10,
      attraction_name: 'Sydney Opera House',
      category: 'Opera House',
      description: 'An iconic symbol of Australia, the Sydney Opera House is a UNESCO World Heritage Site known for its unique architectural design. It hosts performances in music, theater, and opera.',
      best_time_to_visit: 'Evening for a performance or daytime for a tour',
      hours: '09:00 AM to 05:00 PM for tours, evening for performances',
      fee: 'Tour prices start at AUD $42, performance prices vary',
      nearby_attraction: 'Sydney Harbour Bridge, Royal Botanic Garden',
      travel_tips: 'Book tickets in advance for performances. Take a guided tour to learn about the history and architecture.',
      attraction_image_path: 'http://localhost:8080/images/sydney/sydney-opera-house.png'
    },
    {
      id: 47,
      city_id: 10,
      attraction_name: 'Sydney Harbour Bridge',
      category: 'Bridge',
      description: 'One of the most recognizable landmarks in Sydney, the Sydney Harbour Bridge offers stunning views of the harbour and the city. Visitors can walk, drive, or climb the bridge.',
      best_time_to_visit: 'Morning or late afternoon for the best views',
      hours: 'Open 24 hours (BridgeClimb operates from 9:00 AM to 5:00 PM)',
      fee: 'Free to walk or drive across, BridgeClimb prices start at AUD $174',
      nearby_attraction: 'Sydney Opera House, The Rocks',
      travel_tips: 'For a thrilling experience, try the BridgeClimb. Walking across the bridge provides excellent photo opportunities of the Opera House and the harbour.',
      attraction_image_path: 'http://localhost:8080/images/sydney/sydney-harbour-bridge.png'
    },
    {
      id: 48,
      city_id: 10,
      attraction_name: 'Bondi Beach',
      category: 'Beach',
      description: 'Bondi Beach is one of Australia’s most famous beaches, known for its golden sands, surfing spots, and lively atmosphere.',
      best_time_to_visit: 'Morning or late afternoon for cooler weather',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Bondi to Coogee Coastal Walk, Bronte Beach',
      travel_tips: 'Arrive early for a quieter experience. Take the Bondi to Coogee walk for spectacular coastal views.',
      attraction_image_path: 'http://localhost:8080/images/sydney/bondi-beach.png'
    },
    {
      id: 49,
      city_id: 10,
      attraction_name: 'Taronga Zoo',
      category: 'Zoo',
      description: 'Taronga Zoo is home to over 4,000 animals and offers breathtaking views of Sydney Harbour. It’s a great family-friendly attraction to explore Australia’s wildlife.',
      best_time_to_visit: 'Morning for cooler temperatures and active animals',
      hours: '09:30 AM to 05:00 PM',
      fee: 'General admission starts at AUD $49',
      nearby_attraction: 'Bradleys Head, Sydney Harbour National Park',
      travel_tips: 'Take the ferry from Circular Quay for a scenic route to the zoo. Plan at least half a day to explore all the exhibits.',
      attraction_image_path: 'http://localhost:8080/images/sydney/taronga-zoo.png'
    },
    {
      id: 50,
      city_id: 10,
      attraction_name: 'The Rocks',
      category: 'Historic District',
      description: 'The Rocks is one of the oldest parts of Sydney, featuring cobbled streets, historic buildings, and lively markets. It offers a glimpse into the city’s colonial past.',
      best_time_to_visit: 'Weekend mornings for the markets or evenings for dining',
      hours: 'Open 24 hours',
      fee: 'Free entry',
      nearby_attraction: 'Sydney Harbour Bridge, Circular Quay',
      travel_tips: 'Visit on weekends to enjoy the markets. Explore the historic buildings and enjoy the local food scene.',
      attraction_image_path: 'http://localhost:8080/images/sydney/the-rocks.png'
    }
  ]
  );
}
